version: '3.7'

services:
    blackbox-exporter:
      build: .
      container_name: blackbox-exporter
      volumes:
          # - .:/src/blackbox_exporter
          - ./checks/ioplogin.go:/bin/checks/ioplogin.go
          - ./blackbox.yml:/etc/blackbox_exporter/config.yml
      ports: 
          - 9116:9115
      restart: always

    prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
          - "9090:9090"
      restart: always
